version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: make
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: app2-ts
    ports:
      - '8080:8080'
    command: npm run dev
    environment:
      - DB_HOST=mongodb+srv://posfiap:posfiap2@posfiap.hz8ggjd.mongodb.net/PosFiap
      - PORT=8080
      - ID_USUARIO_MP="usuario"
      - ID_EXTERNO_CAIXA="cx01"
      - ACCESS_TOKEN_MP="asd"

