apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-produtos-deployment
  # namespace: postgres
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: postgres-produtos
  template:
    metadata:
      labels:
        app: postgres-produtos
    spec:
      containers:
        - name: postgres-produtos-container
          image: postgres
          envFrom:
            - configMapRef:
                name: db-deployment-produtos-configmap
            - secretRef:
                name:  postgres-produtos-secrets
          ports:
            - containerPort: 5432
          


