apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-produtos-deployment
  # namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-produtos
  template:
    metadata:
      labels:
        app: challenge-produtos
    spec:
      # restartPolicy: Always 
      containers:
        - name: challenge-produtos-container
          image: encortondo/fiap-tech-challenge-produtos
          ports:
            - containerPort: 8082 
          command: ["npm", "run", "start"]
          envFrom:
            - configMapRef:
                name: deployment-produtos-configmap
            - secretRef:
                name:  challenge-produtos-secrets

