apiVersion: v1
kind: Service
metadata:
  name: challenge-produtos-service
  # namespace: challenge
spec:
  selector:
    app: challenge-produtos
  ports:
    - protocol: TCP
      port: 81  # Porta interna do serviço (porta do container)
      targetPort: 8082  # Porta do container
  type: LoadBalancer
